@echo off
:: This script converts a TSV (tab-separated value) spreadsheet file into an Atlas script
:: Each row of the sheet should be formatted as "address | length | original | translation"

:: You can write game translations in Excel/LibreOffice/Google Sheets and insert them into the game using Atlas
:: Input file must use tabs to separate values! You may need to configure your spreadsheet app to export with tabs
:: CSVs (comma-separated values) can cause issues with translation text containing commas or quotation marks

:: Set code page to UTF-8 to support Japanese characters
chcp 65001 >nul 2>&1

:: Use a tab character as the delimiter
set "delimiter=	"

set "inputfile=NEKO.tsv"
set "outputfile=NEKO.txt"

:: Atlas script header - Set file to write into and Shift_JIS table
:: See docs folder at https://github.com/stevemonaco/Atlas
echo //This file was automatically generated by convert_tsv.cmd and is meant to be read by Atlas or abcde.^

//Do not edit this file as changes will be lost. Instead, use a spreadsheet program to edit the tsv files.^

#SETTARGETFILE("insert/NEKO.KSC")^

#VAR(Table, TABLE)^

#ADDTBL("shiftjis.tbl", Table)^

#ACTIVETBL(Table)^

> %outputfile%

setlocal enabledelayedexpansion
:: Read the TSV file line by line, columns 1-4, skipping first line
for /f "usebackq tokens=1-4 skip=1 delims=%delimiter%" %%a in ("%inputfile%") do (
    set "address=%%a"
    set "length=%%b"
    set "original=%%c"
    set "translation=%%d"

    for /f "delims=" %%w in ('python word_wrap.py "!translation!"') do set translation_wrapped=%%w

    echo #JMP($!address!^)
    echo #FIXEDLENGTH(!length!,0^)
    echo //!original!
    echo !translation_wrapped!^<END^>
    :: Insert blank line between sections
    echo.
)>> %outputfile%
endlocal
