#!/usr/bin/env python3
"""
excel_to_atlas.py

Reads an Excel file and writes a text file where each row produces a block like:

#JMP($address)
#FIXEDLENGTH(length,0)
//original
translation<END>

Rows with any blank mapped column are skipped.
Requires: pandas, openpyxl

Usage:
    python excel_to_atlas.py input.xlsx output.txt
    python excel_to_atlas.py input.xlsx output.txt --sheet Sheet1 --cols address,length,original,translation
"""
import argparse
from pathlib import Path
import pandas as pd
import math
import os
import subprocess
import sys
import json

HEADER_LINES = [
    "//This file was automatically generated.",
    "//Do not edit this file as changes will be lost. Instead, use a spreadsheet program to edit the Excel files.",
    "#VAR(Table, TABLE)",
    "#ADDTBL(\"shiftjis.tbl\", Table)",
    "#ACTIVETBL(Table)",
    ""  # blank line after header
]

def is_blank(value):
    if pd.isna(value):
        return True
    if isinstance(value, str) and value.strip() == "":
        return True
    return False

def fmt_cell(value):
    if pd.isna(value):
        return ""
    return str(value)

def fmt_length(value):
    """Return integer length. Raise ValueError if blank or non-numeric."""
    if is_blank(value):
        raise ValueError("length is blank")
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        if math.isnan(value):
            raise ValueError("length is blank")
        return int(value)
    s = str(value).strip()
    try:
        f = float(s)
        return int(f)
    except Exception:
        raise ValueError(f"length value is not numeric: {value!r}")

def wrap_translation(text):
    if text is None or str(text).strip() == "":
        return ""
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"

    # Send the raw text on stdin (avoids shell/arg encoding/quoting issues)
    proc = subprocess.run(
        [sys.executable, "word_wrap.py"],
        input=text,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="strict",
        env=env
    )
    proc.check_returncode()
    return proc.stdout.rstrip("\n")

def row_to_block(row, cols):
    for c in cols:
        if is_blank(row[c]):
            raise ValueError(f"blank value in column '{c}'")
    address = fmt_cell(row[cols[0]]).upper()
    length  = fmt_length(row[cols[1]])
    original_raw = fmt_cell(row[cols[2]])
    original = "\n".join("//" + line for line in original_raw.splitlines())
    translation_raw = fmt_cell(row[cols[3]])
    translation = wrap_translation(translation_raw)
    lines = [
        f"#JMP(${address})",
        f"#FIXEDLENGTH({int(length)},0)",
        f"{original}",
        f"{translation}<END>"
    ]
    return "\n".join(lines)

def main():
    p = argparse.ArgumentParser(description="Convert Excel rows to atlas blocks; skip rows with any blank mapped values.")
    p.add_argument("excel", type=Path, help="Input Excel file (.xlsx/.xls)")
    p.add_argument("output", type=Path, help="Output text file")
    p.add_argument("--sheet", default=0, help="Sheet name or index (default: first sheet)")
    p.add_argument("--cols", default="address,length,original,translation",
                   help="Comma-separated column names in order: address,length,original,translation")
    p.add_argument("--header-row", type=int, default=0,
                   help="Header row index (0-based) for pandas.read_excel; use None if no header")
    args = p.parse_args()

    col_names = [c.strip() for c in args.cols.split(",")]
    if len(col_names) != 4:
        raise SystemExit("ERROR: --cols must list exactly 4 column names in order: address,length,original,translation")

    df = pd.read_excel(args.excel, sheet_name=args.sheet, header=args.header_row)

    for c in col_names:
        if c not in df.columns:
            raise SystemExit(f"ERROR: Column '{c}' not found in sheet. Available columns: {list(df.columns)}")

    blocks = []
    for i, row in df.iterrows():
        # Skip row if any mapped column is blank (NA or empty string)
        if any(is_blank(row[c]) for c in col_names):
            continue
        try:
            blocks.append(row_to_block(row, col_names))
        except ValueError as e:
            raise SystemExit(f"Row {i}: {e}")

    content = HEADER_LINES + (["\n\n".join(blocks)] if blocks else [])
    args.output.write_text("\n".join(content).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {len(blocks)} blocks to {args.output}")

if __name__ == "__main__":
    main()
